### ISSUE TITLE
v0.4.0 Release

### ISSUE THREAD

**Issue by flamusdiu** [lashex/flask-neo4j#9]
There isn't a v0.4.0 tag or release on github. Also, pip still has the older 0.3.0.

**Comment by flamusdiu** [comment]
I see no Python3 support. Any plans for Python3?

**Comment by lashex** [comment]
v0.4.1 is now published to PyPi. 
I have just begun adding Python 3.5 support to another project and will loop around to this one shortly to add the tweaks and testing.

**Comment by flamusdiu** [comment]
@lashex thanks!
